name: Swiftly
description: Install and invoke the Swiftly toolchain manager for Swift

inputs:
  toolchain:
    required: false
    default: ''
    description: >
      A Swift toolchain version to install and select as the default. If omitted, Swiftly will be installed by itself.
      See https://swiftpackageindex.com/swiftlang/swiftly/1.0.0/documentation/swiftlydocs/install-toolchains for a description
      of how to specify a toolchain version.

runs:
  using: composite
  steps:
    - id: platform-check
      name: Check that the current platform is supported
      shell: bash
      run: |
        case '${{ runner.os }}' in
          'Windows')
            echo 'Swiftly does not yet support Windows.'
            exit 1
            ;;
          *)
            ;;
        esac

    - id: curl-install
      name: Make sure curl is available
      shell: bash
      run: |
        command -v curl >/dev/null || {
          if command -v apt-get >/dev/null; then
            apt-get update -q && apt-get install -qy curl
          elif command -v yum >/dev/null; then
            yum install -y curl
          else
            echo "curl is not installed and we couldn't figure out how to install it."
            exit 1
          fi
        }

    - id: swiftly-install
      name: Download and initialize Swiftly
      shell: bash
      run: |
        curl -O "https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz"
        tar zxf "swiftly-$(uname -m).tar.gz"
        ./swiftly init --assume-yes --no-modify-profile --skip-install --quiet-shell-followup
        . ~/.local/share/swiftly/env.sh

    - id: toolchain-install
      name: Install requested Swift toolchain
      if: ${{ inputs.toolchain != '' }}
      shell: bash
      env:
        REQUESTED_TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        swiftly install --assume-yes --use  "${REQUESTED_TOOLCHAIN}"
