name: Swiftly
description: Install and invoke the Swiftly toolchain manager for Swift

inputs:
  toolchain:
    required: false
    default: ''
    description: >
      A Swift toolchain version to install and select as the default. If omitted, Swiftly will be installed by itself.
      See https://swiftpackageindex.com/swiftlang/swiftly/1.0.0/documentation/swiftlydocs/install-toolchains for a description
      of how to specify a toolchain version.

runs:
  using: composite
  steps:
    - id: platform-check
      name: Check that the current platform is supported
      shell: bash
      run: |
        case '${{ runner.os }}' in
          'Windows')
            echo 'Swiftly does not yet support Windows.'
            exit 1
            ;;
          *)
            ;;
        esac

    - id: deps-install
      name: Make sure curl and gpg are available
      shell: bash
      run: |
        command -v curl >/dev/null || {
          if command -v apt-get >/dev/null; then
            apt-get update -q && apt-get install -qy curl
          elif command -v yum >/dev/null; then
            yum install -y curl
          elif command -v brew >/dev/null; then
            brew install curl
          else
            echo "curl is not installed and we couldn't figure out how to install it."
            exit 1
          fi
        }
        command -v gpg >/dev/null || {
          if command -v apt-get >/dev/null; then
            apt-get update -q && apt-get install -qy gpg
          elif command -v yum >/dev/null; then
            yum install -y gpg
          elif command -v brew >/dev/null; then
            brew install gpg
          else
            echo "gpg is not installed and we couldn't figure out how to install it."
            exit 1
          fi
        }

    - id: swiftly-install
      name: Download and initialize Swiftly
      shell: bash
      env:
        RUNNER_OS: ${{ runner.os }}
      run: |
        if [[ "${RUNNER_OS}" == 'Linux' ]]; then
          curl -O "https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz"
          tar zxf "swiftly-$(uname -m).tar.gz"
          SWIFTLY_BIN_PATH="$(pwd)/swiftly"
        elif [[ "${RUNNER_OS}" == 'macOS' ]]; then
          curl -O 'https://download.swift.org/swiftly/darwin/swiftly.pkg'
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
          SWIFTLY_BIN_PATH="${HOME}/local/bin/swiftly"
        else
          echo "Unsupported OS: ${RUNNER_OS}"
          exit 1
        fi
        "${SWIFTLY_BIN_PATH}" init --assume-yes --no-modify-profile --skip-install --quiet-shell-followup
        . "${HOME}/.local/share/swiftly/env.sh"
        echo "SWIFTLY_HOME_DIR=${SWIFTLY_HOME_DIR}" >>"${GITHUB_ENV}"
        echo "SWIFTLY_BIN_DIR=${SWIFTLY_BIN_DIR}" >>"${GITHUB_ENV}"
        echo "${SWIFTLY_BIN_DIR}" >>"${GITHUB_PATH}"

    - id: toolchain-install
      name: Install requested Swift toolchain
      if: ${{ inputs.toolchain != '' }}
      shell: bash
      env:
        REQUESTED_TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        swiftly install --assume-yes --use --post-install-file "${HOME}/.swiftly-postinstall-cmds.sh" "${REQUESTED_TOOLCHAIN}"
        if [[ -f "${HOME}/.swiftly-postinstall-cmds.sh" ]]; then
          export DEBIAN_FRONTEND=noninteractive # prevent Debian/Ubuntu installs from hanging on tzdata
          if [[ "$(id -un)" == 'root' ]]; then
            . "${HOME}/.swiftly-postinstall-cmds.sh"
          else
            sudo bash -c ". '${HOME}/.swiftly-postinstall-cmds.sh'" # use the current value of HOME rather than the subshell's value
          fi
          rm "${HOME}/.swiftly-postinstall-cmds.sh"
        fi
